[package]
name = "librespot-protocol"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
protobuf = "2.4.0"

[build-dependencies]
protobuf-codegen-pure = "2.4.0"
protobuf-codegen = "*"
regex = "1.1.0"
